application: cykloud
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
# web files
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: \1
  upload: (.*\.(appcache|manifest))
  expiration: "0m"

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)
  expiration: "1h"

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: \1
  upload: (.*\.json)
  expiration: "1h"

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: \1
  upload: (.*\.xml)
  expiration: "1h"

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: \1
  upload: (.*\.htc)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: \1
  upload: (.*\.rss)
  expiration: "1h"

- url: /(.*\.atom)
  mime_type: application/atom+xml
  static_files: \1
  upload: (.*\.atom)
  expiration: "1h"

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: \1
  upload: (.*\.crx)

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: \1
  upload: (.*\.xpi)

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: \1
  upload: (.*\.safariextz)

# index files
- url: /(.*)/
  static_files: \1/index.html
  upload: (.*)/index.html
  expiration: "15m"

# site root
- url: /
  static_files: index.html
  upload: index.html
  expiration: "15m"